### ISSUE TITLE
Warning email from Google re: Google+ API

### ISSUE THREAD

**Issue by imkane** [passport/discuss#17]
We got this email from Google recently:

> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature (https://developers.google.com/+/web/signin/) to the more comprehensive Google Sign-in (https://developers.google.com/identity/) authentication system.

Then we noticed in the Google Developer portal that our project has had 134 calls to **plus.people.get** in the last month.

We're using https://github.com/jaredhanson/passport-google-oauth for Google Sign-in.

But we searched our entire code, even node_modules, and couldn't find any reference to **plus.people.get**.

Any ideas where this is coming from? And how we can update our code to avoid Google Sign-in issues come March?

Thanks!

**Comment by stelian87** [comment]
Hello,
i'm having the same issue. i'm using OAuth2Strategy
Now from what i've read online i found the following:
1. passport-google-oauth combines passport-google-oauth1 and passport-google-oauth20. 
2. passport-google-oauth20 provides userProfileURL: 'https://www.googleapis.com/oauth2/v3/userinfo', in the strategy options (use the oauth userinfo endpoint instead of G+) for a fix. (source: https://github.com/jaredhanson/passport-google-oauth2/pull/51 )

Is it fair to assume that this issue is fixed?

**Comment by imkane** [comment]
@stelian87 if your Google Developer portal shows recent calls to **plus.people.get** then I think it's safe to assume this issue is **not fixed**

**Comment by jaredhanson** [comment]
`passport-google-oauth20@2.0.0`, which migrates away from the Google+ API, has been published to npm.

More information here: https://medium.com/passportjs/google-api-shutdown-330c3b47e3df
